stages:
  - build
  - trigger

.build:
  stage: build
  script:
    - sh ${VENDOR_SCRIPT} minizinc-vendor master vendor:${MZNARCH} vendor.zip
    - unzip -q vendor.zip
    - sh ${VENDOR_SCRIPT} minizinc develop build:${MZNARCH} minizinc.zip
    - unzip -q minizinc.zip
    - cmake -S . -B build -G"$CMAKE_ARCH" -DCMAKE_BUILD_TYPE=Release -DUSE_SYSTEM_LIBMINIZINC=1 -Dlibminizinc_DIR=$CI_PROJECT_DIR/minizinc/$CMAKEDIR/libminizinc -DGecode_ROOT="$CI_PROJECT_DIR/vendor/gecode" -DOsiCBC_ROOT="$CI_PROJECT_DIR/vendor/cbc" -DHIGHS_DIR="$CI_PROJECT_DIR/vendor/highs/$CMAKEDIR/highs" -DCMAKE_INSTALL_PREFIX="$CI_PROJECT_DIR/mzn-analyse"
    - cmake --build build --config Release --target install
  artifacts:
    paths:
      - mzn-analyse/
  cache:
    key: "$CI_JOB_NAME"
    paths: [minizinc.zip*, vendor.zip*]

build:linux:
  extends: .build
  image: ghcr.io/minizinc/docker-build-environment:cpp
  variables:
    MZNARCH: "linux"
    CMAKE_ARCH: "Ninja"
    CMAKEDIR: "lib64/cmake"
  tags: [linux, docker]

build:osx:
  extends: .build
  variables:
    MZNARCH: "osx"
    CMAKE_ARCH: "Ninja"
    CMAKEDIR: "lib/cmake"
    MACOSX_DEPLOYMENT_TARGET: "10.9"
    CMAKE_OSX_ARCHITECTURES: "x86_64;arm64"
  tags: [osx, cmake, cpp]

build:win64:
  extends: .build
  variables:
    MZNARCH: "win64"
    CMAKEDIR: "CMake/libminizinc"
    CMAKE_ARCH: "Ninja"
  script:
    - sh %VENDOR_SCRIPT% minizinc-vendor master vendor:%MZNARCH% vendor.zip
    - unzip -q vendor.zip
    - sh %VENDOR_SCRIPT% minizinc develop build:%MZNARCH% minizinc.zip
    - unzip -q minizinc.zip
    - cmake -S . -B build -G"%CMAKE_ARCH%" -DCMAKE_BUILD_TYPE=Release -DUSE_SYSTEM_LIBMINIZINC=1 -Dlibminizinc_DIR="%CI_PROJECT_DIR%/minizinc/%CMAKEDIR%" -DGecode_ROOT="%CI_PROJECT_DIR%/vendor/gecode" -DOsiCBC_ROOT="%CI_PROJECT_DIR%/vendor/cbc" -DHIGHS_DIR="%CI_PROJECT_DIR%/vendor/highs/lib/cmake/highs" -DCMAKE_INSTALL_PREFIX="%CI_PROJECT_DIR%/mzn-analyse"
    - cmake --build build --config Release --target install
  cache:
    key: "build_win64"
  tags: [win64, cmake, cpp]

# ----------- Trigger MiniZincIDE pipeline -----------

trigger:ide:
  stage: trigger
  trigger:
    project: minizinc/minizinc-ide
    branch: develop
  only: [develop]
